# Generated by Django 5.0.2 on 2024-02-21 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuppleezApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandes',
            name='cours_optionnel',
            field=models.CharField(choices=[('selectionnez', 'selectionnez'), ('Oui', 'Oui'), ('Non', 'Non')], default='selectionnez', max_length=200),
        ),
        migrations.AlterField(
            model_name='demandes',
            name='date_soumission',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 11, 17, 45, 427540, tzinfo=datetime.timezone.utc)),
        ),
    ]
