# Generated by Django 5.0.2 on 2024-02-21 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuppleezApp', '0003_alter_demandes_cours_optionnel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='Cours_optionnel',
        ),
        migrations.AlterField(
            model_name='archiveadmin',
            name='date_soumission',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 18, 38, 47, 195208, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='demandes',
            name='date_soumission',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 18, 38, 47, 194522, tzinfo=datetime.timezone.utc)),
        ),
    ]
