# Generated by Django 5.0.2 on 2024-02-21 19:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuppleezApp', '0004_remove_cours_cours_optionnel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandes',
            name='date_soumission',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 19, 6, 20, 822924, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ArchiveDemandeSupprime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours_optionnel', models.CharField(choices=[('', 'Sélectionnez une option'), ('Oui', 'Oui'), ('Non', 'Non')], default='Veuillez sélectionner', max_length=200)),
                ('confirmation_Pour_cours_optionnel', models.CharField(max_length=50)),
                ('suppleant', models.CharField(max_length=200)),
                ('Motif', models.TextField()),
                ('cpo', models.CharField(blank=True, max_length=200, null=True)),
                ('Accord_suppleant', models.CharField(max_length=200)),
                ('remarque', models.TextField()),
                ('num_poste', models.CharField(max_length=200)),
                ('salaire', models.DecimalField(decimal_places=3, default=0, max_digits=100)),
                ('Accord_CF', models.CharField(max_length=200)),
                ('date_soumission', models.DateField(default=datetime.datetime(2024, 2, 21, 19, 6, 20, 825532, tzinfo=datetime.timezone.utc))),
                ('statut_demande', models.CharField(choices=[('Approuvé', 'Approuvé'), ('Refusé', 'Refusé')], default='En cours de traitement', max_length=200)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuppleezApp.cours')),
                ('imputation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuppleezApp.imputationsalaire')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Demandes supprimés',
            },
        ),
        migrations.CreateModel(
            name='ArchiveDemandeTraite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours_optionnel', models.CharField(choices=[('', 'Sélectionnez une option'), ('Oui', 'Oui'), ('Non', 'Non')], default='Veuillez sélectionner', max_length=200)),
                ('confirmation_Pour_cours_optionnel', models.CharField(max_length=50)),
                ('suppleant', models.CharField(max_length=200)),
                ('Motif', models.TextField()),
                ('cpo', models.CharField(blank=True, max_length=200, null=True)),
                ('Accord_suppleant', models.CharField(max_length=200)),
                ('remarque', models.TextField()),
                ('num_poste', models.CharField(max_length=200)),
                ('salaire', models.DecimalField(decimal_places=3, default=0, max_digits=100)),
                ('Accord_CF', models.CharField(max_length=200)),
                ('date_soumission', models.DateField(default=datetime.datetime(2024, 2, 21, 19, 6, 20, 824297, tzinfo=datetime.timezone.utc))),
                ('statut_demande', models.CharField(choices=[('Approuvé', 'Approuvé'), ('Refusé', 'Refusé')], default='En cours de traitement', max_length=200)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuppleezApp.cours')),
                ('imputation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuppleezApp.imputationsalaire')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Demandes traités',
            },
        ),
        migrations.DeleteModel(
            name='ArchiveAdmin',
        ),
    ]
