# Generated by Django 5.0.2 on 2024-02-21 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuppleezApp', '0006_alter_archivedemandesupprime_cours_optionnel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterModelOptions(
            name='demandes',
            options={'verbose_name_plural': 'Demandes en cours'},
        ),
        migrations.AlterField(
            model_name='archivedemandesupprime',
            name='Accord_suppleant',
            field=models.CharField(choices=[('', 'Sélectionnez une option'), ('Oui', 'Oui'), ('Non', 'Non')], default='Sélectionnez une option', max_length=200),
        ),
        migrations.AlterField(
            model_name='archivedemandesupprime',
            name='date_soumission',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 21, 11, 46, 986214, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='archivedemandesupprime',
            name='num_poste',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='archivedemandesupprime',
            name='remarque',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archivedemandesupprime',
            name='salaire',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='archivedemandetraite',
            name='Accord_suppleant',
            field=models.CharField(choices=[('', 'Sélectionnez une option'), ('Oui', 'Oui'), ('Non', 'Non')], default='Sélectionnez une option', max_length=200),
        ),
        migrations.AlterField(
            model_name='archivedemandetraite',
            name='date_soumission',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 21, 11, 46, 985365, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='archivedemandetraite',
            name='num_poste',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='archivedemandetraite',
            name='remarque',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archivedemandetraite',
            name='salaire',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='demandes',
            name='Accord_suppleant',
            field=models.CharField(choices=[('', 'Sélectionnez une option'), ('Oui', 'Oui'), ('Non', 'Non')], default='Sélectionnez une option', max_length=200),
        ),
        migrations.AlterField(
            model_name='demandes',
            name='date_soumission',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 21, 11, 46, 984446, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='demandes',
            name='num_poste',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='demandes',
            name='remarque',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandes',
            name='salaire',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=100, null=True),
        ),
    ]
