# Generated by Django 5.0.2 on 2024-02-21 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuppleezApp', '0007_alter_cours_options_alter_demandes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedemandesupprime',
            name='date_soumission',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 23, 17, 48, 413090, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='archivedemandetraite',
            name='date_soumission',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 23, 17, 48, 412456, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='demandes',
            name='date_soumission',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 23, 17, 48, 411770, tzinfo=datetime.timezone.utc)),
        ),
    ]
